In [4]:
import pandas as pd

In [5]:
print(pd.__version__)

2.3.3

In [9]:
data={
"Name":["Ali","Sara","Jhon"],
"Age":[22,25,21],
"Salary":[30000,45000,50000]
}
df=pd.DataFrame(data)
df

   Name  Age  Salary
0   Ali   22   30000
1  Sara   25   45000
2  Jhon   21   50000

In [11]:
data={
"Name":["Siya","Nina","ken"],
"Marks":[70,80,90],
"city":["jsr","pune","bokaro"]
}
df=pd.DataFrame(data)
df

   Name  Marks    city
0  Siya     70     jsr
1  Nina     80    pune
2   ken     90  bokaro

In [18]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\ASUS 1\Downloads\archive\Amazon Sale Report.csv")
df

C:\Users\ASUS 1\AppData\Local\Temp\ipykernel_16728\3005046150.py:2: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\ASUS 1\Downloads\archive\Amazon Sale Report.csv")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [19]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [20]:
df.tail()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [24]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [22]:
df.shape

(128975, 24)

In [27]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [28]:
len(df)

128975

In [30]:
df["ship-state"].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'Gujarat', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'Goa', 'MEGHALAYA', 'GOA',
       'TRIPURA', 'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'Delhi', nan,
       'ANDAMAN & NICOBAR ', 'Punjab', 'Rajshthan', 'Manipur',
       'rajasthan', 'Odisha', 'NL', 'Bihar', 'MIZORAM', 'punjab',
       'New Delhi', 'Rajasthan', 'Punjab/Mohali/Zirakpur', 'Puducherry',
       'delhi', 'RJ', 'Chandigarh', 'orissa', 'LAKSHADWEEP', 'goa', 'PB',
       'APO', 'Arunachal Pradesh', 'AR', 'Pondicherry', 'Sikkim',
       'Arunachal pradesh', 'Nagaland', 'bihar', 'Mizoram', 'rajsthan',
       'Orissa', 'Rajsthan', 'Meghalaya'], dtype=object)

In [32]:
df["ship-state"].nunique()

69

In [34]:
df["Status"].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [36]:
df["Status"]

0                            Cancelled
1         Shipped - Delivered to Buyer
2                              Shipped
3                            Cancelled
4                              Shipped
                      ...
128970                         Shipped
128971                         Shipped
128972                         Shipped
128973                         Shipped
128974                         Shipped
Name: Status, Length: 128975, dtype: object

In [38]:
df[["Status","ship-state","Amount"]]

                              Status    ship-state   Amount
0                          Cancelled   MAHARASHTRA   647.62
1       Shipped - Delivered to Buyer     KARNATAKA   406.00
2                            Shipped   MAHARASHTRA   329.00
3                          Cancelled    PUDUCHERRY   753.33
4                            Shipped    TAMIL NADU   574.00
...                              ...           ...      ...
128970                       Shipped     TELANGANA   517.00
128971                       Shipped       HARYANA   999.00
128972                       Shipped     TELANGANA   690.00
128973                       Shipped       Gujarat  1199.00
128974                       Shipped  CHHATTISGARH   696.00

[128975 rows x 3 columns]

In [39]:
df[["Status","ship-state","Amount"]].head()

                         Status   ship-state  Amount
0                     Cancelled  MAHARASHTRA  647.62
1  Shipped - Delivered to Buyer    KARNATAKA  406.00
2                       Shipped  MAHARASHTRA  329.00
3                     Cancelled   PUDUCHERRY  753.33
4                       Shipped   TAMIL NADU  574.00

In [50]:
df[["Category","Amount"]]

             Category   Amount
0                 Set   647.62
1               kurta   406.00
2               kurta   329.00
3       Western Dress   753.33
4                 Top   574.00
...               ...      ...
128970          kurta   517.00
128971            Set   999.00
128972  Western Dress   690.00
128973            Set  1199.00
128974            Set   696.00

[128975 rows x 2 columns]

In [52]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [57]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [59]:
df["Category"].value_counts()

Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [61]:
df["Amount"].mean()

np.float64(648.5614647631622)

In [63]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [65]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
Unnamed: 22            object
dtype: object

In [67]:
df.duplicated().sum()

np.int64(0)

In [69]:
df.groupby("Category")["Amount"].mean().sort_values(ascending=False).head(10)

Category
Set              833.385571
Saree            799.572645
Western Dress    762.790580
Ethnic Dress     723.895389
Top              526.098603
Blouse           520.327106
kurta            455.927108
Bottom           358.733286
Dupatta          305.000000
Name: Amount, dtype: float64

In [70]:
df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

Category
Set              39204124.03
kurta            21299546.70
Western Dress    11216072.69
Top               5347792.30
Ethnic Dress       791217.66
Blouse             458408.18
Bottom             150667.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [75]:
df.isnull().sum().sort_values(ascending=False)

fulfilled-by          89698
promotion-ids         49153
Unnamed: 22           49050
currency               7795
Amount                 7795
Courier Status         6872
ship-country             33
ship-postal-code         33
ship-state               33
ship-city                33
ship-service-level        0
Style                     0
Date                      0
B2B                       0
Status                    0
Fulfilment                0
Sales Channel             0
Qty                       0
Order ID                  0
ASIN                      0
Size                      0
Category                  0
SKU                       0
index                     0
dtype: int64

In [80]:
df["Unnamed: 22"].head(200000)

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
128970    False
128971    False
128972    False
128973    False
128974    False
Name: Unnamed: 22, Length: 128975, dtype: object

In [81]:
df["Unnamed: 22"].value_counts(dropna=False)

Unnamed: 22
False    79925
NaN      49050
Name: count, dtype: int64

In [90]:
df["fulfilled-by"].value_counts(dropna=False)

fulfilled-by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [92]:
df[df["Amount"].isnull()].head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
29,29,404-5933402-8801952,04-30-22,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,...,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False,Easy Ship,NaN
65,65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,...,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False,NaN,NaN
84,84,403-9950518-0349133,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,...,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,NaN,False,NaN,NaN
95,95,405-9112089-3379536,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,...,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,NaN,False,NaN,NaN
101,101,402-7841951-1872363,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET347,SET347-KR-NP-S,Set,...,NaN,NaN,NEW DELHI,DELHI,110036.0,IN,NaN,False,NaN,NaN
132,132,171-0293372-4913973,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET269,SET269-KR-NP-XXXL,Set,...,NaN,NaN,KOLAR,KARNATAKA,563101.0,IN,NaN,False,NaN,NaN
139,139,403-6442534-2769112,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,J0300,J0300-TP-XXXL,Top,...,NaN,NaN,AZAMGARH,UTTAR PRADESH,276302.0,IN,NaN,False,NaN,NaN
155,155,402-8078642-8565124,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3887,JNE3887-KR-XL,kurta,...,NaN,NaN,Puri-2,ODISHA,752002.0,IN,NaN,False,NaN,NaN
165,165,406-0218328-1773963,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,PJNE2100,PJNE2100-KR-N-6XL,kurta,...,NaN,NaN,WALAJAPET,TAMIL NADU,632513.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN

In [93]:
df["currency"].value_counts(dropna=False)

currency
INR    121180
NaN      7795
Name: count, dtype: int64

In [101]:
df[df["currency"].isnull()].head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
8,8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
29,29,404-5933402-8801952,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,...,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False,Easy Ship,NaN
65,65,171-4137548-0481151,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,...,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False,NaN,NaN
84,84,403-9950518-0349133,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,...,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,NaN,False,NaN,NaN
95,95,405-9112089-3379536,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,...,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,NaN,False,NaN,NaN
101,101,402-7841951-1872363,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET347,SET347-KR-NP-S,Set,...,NaN,NaN,NEW DELHI,DELHI,110036.0,IN,NaN,False,NaN,NaN
132,132,171-0293372-4913973,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET269,SET269-KR-NP-XXXL,Set,...,NaN,NaN,KOLAR,KARNATAKA,563101.0,IN,NaN,False,NaN,NaN
139,139,403-6442534-2769112,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,J0300,J0300-TP-XXXL,Top,...,NaN,NaN,AZAMGARH,UTTAR PRADESH,276302.0,IN,NaN,False,NaN,NaN
155,155,402-8078642-8565124,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3887,JNE3887-KR-XL,kurta,...,NaN,NaN,Puri-2,ODISHA,752002.0,IN,NaN,False,NaN,NaN
165,165,406-0218328-1773963,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,PJNE2100,PJNE2100-KR-N-6XL,kurta,...,NaN,NaN,WALAJAPET,TAMIL NADU,632513.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN

In [105]:
df["Date"]=pd.to_datetime(df["Date"],dayfirst = True)

In [106]:
df["Date"].head(10)

0   2022-04-30
1   2022-04-30
2   2022-04-30
3   2022-04-30
4   2022-04-30
5   2022-04-30
6   2022-04-30
7   2022-04-30
8   2022-04-30
9   2022-04-30
Name: Date, dtype: datetime64[ns]

In [107]:
df["Date"] = pd.to_datetime(df["Date"], format="%m-%d-%Y")

In [109]:
df["Amount"].dtype

dtype('float64')

In [115]:
df["Category"] = df["Category"].str.strip()

In [116]:
df["Status"] = df["Status"].str.strip()

In [117]:
df["Category"].value_counts()

Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [118]:
df["Status"].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [126]:
df["ship-city"].value_counts().head(50)

ship-city
BENGALURU             11900
HYDERABAD              9128
MUMBAI                 7124
NEW DELHI              6340
CHENNAI                6288
PUNE                   4618
KOLKATA                2844
GURUGRAM               1956
THANE                  1877
LUCKNOW                1627
NOIDA                  1627
GHAZIABAD              1485
AHMEDABAD              1445
NAVI MUMBAI            1403
BANGALORE              1362
JAIPUR                 1062
COIMBATORE              891
VISAKHAPATNAM           858
FARIDABAD               820
PATNA                   816
BHUBANESWAR             780
PIMPRI CHINCHWAD        754
GUWAHATI                740
NAGPUR                  733
VADODARA                710
THIRUVANANTHAPURAM      679
DEHRADUN                633
SECUNDERABAD            623
GREATER NOIDA           564
SURAT                   564
INDORE                  557
KALYAN                  547
KANPUR                  541
ERNAKULAM               520
BHOPAL                  502
RANCHI                  482
VIJAYAWADA              479
MYSURU                  423
GUNTUR                  422
VARANASI                387
NASHIK                  380
DELHI                   361
MANGALURU               358
GURGAON                 338
VASAI VIRAR             331
ALLAHABAD               324
CHANDIGARH              324
JAMSHEDPUR              306
THRISSUR                295
NELLORE                 286
Name: count, dtype: int64

In [120]:
df["ship-city"]=df["ship-city"].str.upper()

In [121]:
df["ship-city"]=df["ship-city"].str.strip().str.replace(".","",regex=False)

In [127]:
df["ship-city"].unique()

array(['MUMBAI', 'BENGALURU', 'NAVI MUMBAI', ..., 'CHERUKUNNU (PO)',
       'GULABPURA, DISTT BHILWARA', 'PRAYAGRAJ (ALLAHABAD)'],
      shape=(7273,), dtype=object)

In [129]:
df["ship-city"].head(20)

0          MUMBAI
1       BENGALURU
2     NAVI MUMBAI
3      PUDUCHERRY
4         CHENNAI
5       GHAZIABAD
6      CHANDIGARH
7       HYDERABAD
8       HYDERABAD
9         CHENNAI
10        CHENNAI
11          NOIDA
12       AMRAVATI
13         MUMBAI
14         MUMBAI
15       GUNTAKAL
16         JAIPUR
17      NEW DELHI
18        GURGAON
19      BENGALURU
Name: ship-city, dtype: object

In [131]:
df["Amount"].describe()

count    121180.000000
mean        648.561465
std         281.211687
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [134]:
df[df["Amount"] == 0][["Status","Amount"]].value_counts()

Status                         Amount
Shipped                        0.0       1518
Shipped - Delivered to Buyer   0.0        716
Shipped - Returned to Seller   0.0         51
Shipped - Picked Up            0.0         28
Pending                        0.0         17
Pending - Waiting for Pick Up  0.0          9
Shipped - Lost in Transit      0.0          2
Shipped - Returning to Seller  0.0          2
Name: count, dtype: int64

In [135]:
df[df["Amount"]==0].head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
212,212,408-4547464-4180323,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3568,JNE3568-KR-XXL,kurta,...,INR,0.0,BHUBANESWAR,ODISHA,752054.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
374,374,408-5020509-5674715,2022-04-30,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE3798,JNE3798-KR-M,Western Dress,...,INR,0.0,NEW DELHI,DELHI,110096.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
385,385,408-3137526-3167563,2022-04-30,Shipped,Amazon,Amazon.in,Standard,JNE3405,JNE3405-KR-L,kurta,...,INR,0.0,DARJEELING,WEST BENGAL,734101.0,IN,NaN,False,NaN,NaN
388,388,408-7971979-8745937,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0401,J0401-DR-XS,Western Dress,...,INR,0.0,LUDHIANA,PUNJAB,141001.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
392,392,408-0912805-7526753,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,SET365,SET365-KR-NP-L,Set,...,INR,0.0,MUMBAI,MAHARASHTRA,400101.0,IN,NaN,False,NaN,NaN
436,436,408-6466311-6949931,2022-04-30,Shipped,Amazon,Amazon.in,Standard,SET014,SET014-KR-PP-XXL,Set,...,INR,0.0,LUCKNOW,UTTAR PRADESH,226002.0,IN,NaN,False,NaN,NaN
441,441,408-6732772-4525113,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0010,J0010-LCD-XS,Set,...,INR,0.0,AURANGABAD,MAHARASHTRA,431002.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
446,446,408-7937211-8974712,2022-04-30,Shipped,Amazon,Amazon.in,Standard,SET324,SET324-KR-NP-L,Set,...,INR,0.0,SHIRDI,MAHARASHTRA,423109.0,IN,NaN,False,NaN,NaN
449,449,408-6348199-2089932,2022-04-30,Shipped,Amazon,Amazon.in,Standard,J0283,J0283-SET-XL,Set,...,INR,0.0,RANCHI,JHARKHAND,834002.0,IN,NaN,False,NaN,NaN
729,729,408-4193711-8156307,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0215,J0215-BL-L,Blouse,...,INR,0.0,KARIMGANJ,ASSAM,788710.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN

In [136]:
df["Qty"].value_counts().sort_index()

Qty
0      12807
1     115780
2        341
3         32
4          9
5          2
8          1
9          1
13         1
15         1
Name: count, dtype: int64

In [138]:
df[df["Qty"]==0]["Status"].value_counts()

Status
Cancelled                       12701
Shipped                            93
Shipped - Delivered to Buyer        8
Shipped - Returned to Seller        3
Pending                             2
Name: count, dtype: int64

In [140]:
df[df["Category"] == "Set"].head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
5,5,404-1490984-4578765,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,6,408-5748499-6859555,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
8,8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
13,13,408-7955685-3083534,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,SET182,SET182-KR-DH-XS,Set,...,INR,657.00,MUMBAI,MAHARASHTRA,400053.0,IN,NaN,False,NaN,NaN

In [143]:
df["Order ID"].duplicated().sum()

np.int64(8597)

In [144]:
df[df["Order ID"] == df["Order ID"].iloc[0]]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN

In [146]:
df.duplicated().sum()

np.int64(0)

In [149]:
df[df[["ship-city","ship-state","ship-postal-code","ship-country"]].isnull().any(axis=1)]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
1871,1871,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-L,Top,...,INR,493.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
1872,1872,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,kurta,...,INR,458.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
8752,8752,406-4003386-8768363,2022-04-25,Shipped,Amazon,Amazon.in,Expedited,JNE3376,JNE3376-KR-M,kurta,...,INR,432.0,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
11215,11215,402-0107720-7057168,2022-04-23,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,654.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
13252,13252,407-4532637-8415521,2022-04-22,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,INR,380.0,NaN,NaN,NaN,NaN,NaN,False,Easy Ship,NaN
15688,15688,404-9229894-8608305,2022-04-21,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,...,INR,442.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
16787,16787,402-4919636-4333150,2022-04-20,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE1233,JNE1233-BLUE-KR-031-XXXL,kurta,...,INR,376.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
18351,18351,405-4927647-8064368,2022-04-19,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-XS,Set,...,INR,1112.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
22930,22930,402-8628677-0457954,2022-04-16,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,J0003,J0003-SET-S,Set,...,INR,654.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
24986,24986,406-4079063-8291520,2022-04-15,Cancelled,Amazon,Amazon.in,Expedited,JNE3567,JNE3567-KR-XXL,kurta,...,INR,399.0,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
30379,30379,404-7506843-7913132,2022-12-04,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET350,SET350-KR-NP-L,Set,...,INR,1299.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
37963,37963,407-3064376-9158743,2022-08-04,Cancelled,Merchant,Amazon.in,Standard,JNE3567,JNE3567-KR-M,kurta,...,INR,380.0,NaN,NaN,NaN,NaN,NaN,False,Easy Ship,NaN
37964,37964,407-3064376-9158743,2022-08-04,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,INR,380.0,NaN,NaN,NaN,NaN,NaN,False,Easy Ship,NaN
60986,60986,171-3257610-9237139,2022-05-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3365,JNE3365-KR-1052-A-L,kurta,...,INR,376.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
63040,63040,402-1049475-3611523,2022-05-20,Shipped,Amazon,Amazon.in,Expedited,JNE3739,JNE3739-KR-XXL,kurta,...,INR,459.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
73675,73675,405-1356730-8598722,2022-11-05,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET187,SET187-KR-DH-XL,Set,...,INR,699.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
73746,73746,407-4664354-2179554,2022-11-05,Shipped,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,...,INR,666.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
73771,73771,406-7680604-5439529,2022-11-05,Shipped,Amazon,Amazon.in,Expedited,PJNE3607,PJNE3607-KR-4XL,kurta,...,INR,869.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
73772,73772,406-7680604-5439529,2022-11-05,Shipped,Amazon,Amazon.in,Expedited,PJNE3368,PJNE3368-KR-4XL,kurta,...,INR,869.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
73911,73911,405-3420451-5230744,2022-11-05,Cancelled,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False
80011,80011,171-4552355-0255565,2022-07-05,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET324,SET324-KR-NP-XL,Set,...,INR,607.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
80092,80092,403-2857451-7335536,2022-07-05,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-S,kurta,...,INR,467.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
80455,80455,171-4691098-8489159,2022-06-05,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET183,SET183-KR-DH-M,Set,...,INR,759.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
84008,84008,405-8605864-8021901,2022-04-05,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE1951,JNE1951-KR-155-XXL,kurta,...,INR,368.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
84757,84757,402-8651786-0683548,2022-04-05,Shipped,Amazon,Amazon.in,Expedited,JNE3690,JNE3690-TU-XL,Top,...,INR,487.0,NaN,NaN,NaN,NaN,NaN,False,NaN,False
104201,104201,403-3190636-2013146,2022-06-18,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-S,Set,...,INR,792.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
106498,106498,402-8673941-7883531,2022-06-16,Cancelled,Amazon,Amazon.in,Expedited,JNE3734,JNE3734-KR-XL,kurta,...,NaN,NaN,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
124215,124215,405-0340492-2359532,2022-04-06,Cancelled,Amazon,Amazon.in,Expedited,JNE3465,JNE3465-KR-L,kurta,...,INR,491.0,NaN,NaN,NaN,NaN,NaN,False,NaN,False
124357,124357,405-5884153-9925116,2022-04-06,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,kurta,...,INR,486.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
124358,124358,405-5884153-9925116,2022-04-06,Shipped,Amazon,Amazon.in,Expedited,SET337,SET337-KR-NP-L,Set,...,INR,874.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
124359,124359,405-5884153-9925116,2022-04-06,Shipped,Amazon,Amazon.in,Expedited,SET154,SET154-KR-NP-L,Set,...,INR,832.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
125385,125385,403-5172380-9787567,2022-03-06,Shipped,Amazon,Amazon.in,Expedited,JNE3366,JNE3366-KR-1053-L,kurta,...,INR,376.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
126620,126620,403-4249038-6582716,2022-02-06,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-M,Western Dress,...,INR,735.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False

In [150]:
df = df.drop(columns="Unnamed: 22")

In [154]:
df.to_csv("amazon_orders_cleaned.csv",index=False)

In [155]:
df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

Category
Set              39204124.03
kurta            21299546.70
Western Dress    11216072.69
Top               5347792.30
Ethnic Dress       791217.66
Blouse             458408.18
Bottom             150667.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [156]:
df.groupby("Category")["Qty"].sum().sort_values(ascending=False)

Category
Set              45289
kurta            45045
Western Dress    13943
Top               9903
Ethnic Dress      1053
Blouse             863
Bottom             398
Saree              152
Dupatta              3
Name: Qty, dtype: int64

In [1]:
import os
os.getcwd()

'C:\\Users\\ASUS 1'

In [2]:
os.listdir()

['.anaconda',
 '.android',
 '.conda',
 '.continuum',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.virtual_documents',
 '.vscode',
 '.vscode-shared',
 'amazon_orders_cleaned.csv',
 'anaconda3',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'New folder',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{13c28a8d-36ed-11f0-8b4d-a8e291286d6f}.TM.blf',
 'NTUSER.DAT{13c28a8d-36ed-11f0-8b4d-a8e291286d6f}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{13c28a8d-36ed-11f0-8b4d-a8e291286d6f}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'op_sun_pandas.ipynb',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled Folder',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos']

In [4]:
import os
os.startfile(os.getcwd())